# Use an official Python runtime as a base image
FROM python:3.10-slim

# Set the working directory
WORKDIR /code

# Copy the current directory contents into the container
COPY ./requirements.txt /code/requirements.txt

# Install required Python packages
RUN pip install --no-cache-dir --upgrade -r requirements.txt
RUN pip uninstall bitsandbytes
RUN pip install -U bitsandbytes
RUN pip install fastapi[standard]

COPY ./main.py /code/

# Command to run FastAPI app
CMD ["fastapi", "run", "main.py" ,"--port", "80"]