// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2dDQQAgRpKX_B6BJkh9vMz1wHL1-8720',
    appId: '1:512735207586:web:e379d77a2d175a45b137fb',
    messagingSenderId: '512735207586',
    projectId: 'resurrectai-4ce10',
    authDomain: 'resurrectai-4ce10.firebaseapp.com',
    storageBucket: 'resurrectai-4ce10.appspot.com',
    measurementId: 'G-49NC6JK8Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmbZACWdM7cn7CvD22F2eV_xbvVjSUAdk',
    appId: '1:512735207586:android:8ed28a1df70aa275b137fb',
    messagingSenderId: '512735207586',
    projectId: 'resurrectai-4ce10',
    storageBucket: 'resurrectai-4ce10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIWciw1nAIRuNL_MwjEknoAT4uA9wFBRo',
    appId: '1:512735207586:ios:57f76a64a01ba452b137fb',
    messagingSenderId: '512735207586',
    projectId: 'resurrectai-4ce10',
    storageBucket: 'resurrectai-4ce10.appspot.com',
    iosBundleId: 'com.example.resurrectai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIWciw1nAIRuNL_MwjEknoAT4uA9wFBRo',
    appId: '1:512735207586:ios:57f76a64a01ba452b137fb',
    messagingSenderId: '512735207586',
    projectId: 'resurrectai-4ce10',
    storageBucket: 'resurrectai-4ce10.appspot.com',
    iosBundleId: 'com.example.resurrectai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2dDQQAgRpKX_B6BJkh9vMz1wHL1-8720',
    appId: '1:512735207586:web:e8d82642ade9e7aab137fb',
    messagingSenderId: '512735207586',
    projectId: 'resurrectai-4ce10',
    authDomain: 'resurrectai-4ce10.firebaseapp.com',
    storageBucket: 'resurrectai-4ce10.appspot.com',
    measurementId: 'G-01CJK7CS17',
  );
}
